name: articles
description: A new Flutter project.
publish_to: 'none' 


environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dio: ^5.3.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  retrofit: ^4.0.1
  get_it: ^7.6.0
  injectable: ^2.1.2
  freezed: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  retrofit_generator: ^7.0.8
  injectable_generator: ^2.1.6
flutter:

  uses-material-design: true
